name: Auto Publish to npm with Version Bump

on:
  push:
    branches:
      - main

# Add permissions at the workflow level
permissions:
  contents: write

jobs:
  version-bump-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # Explicitly add token

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
          auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Bump version (patch)
        run: npm version patch -m "ci bump version to %s [skip ci]"

      - name: Push version bump commit and tags
        run: |
          git push origin HEAD:main --follow-tags
          git push --tags

      - name: Build (if necessary)
        run: npm run build || echo "No build step"

      - name: Publish to npm
        run: npm publish --access public
